package mx.com.teclo.sms.ws.persistencia.mybatis.dao.reportes;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import mx.com.teclo.sms.ws.persistencia.vo.reportes.InfraccionesPorZonaVialVO;

@Mapper
public interface ReportesMybatisDAO {

	String GET_INFRACCIONES_POR_ZONA_VIAL = "SELECT ZONAV.NB_ZONA_VIAL as ZONAVIAL, "
	+ "TIPO_INFRACCIONES.NB_TIPO_INFRACCION as TIPOINFRACCION, TIPO_INFRACCIONES.CD_TIPO_INFRACCION as CODIGOINFRACCION, "
	+ "COUNT(EVENTOS.EVENTO_INFRAC_NUM) as TOTALINFRACCIONES, round(100*ratio_to_report(count(EVENTOS.EVENTO_INFRAC_NUM)) over (), 2) PORCENTAJEINFRACCIONES "
    + "FROM TSAI001C_TIPO_INFRACCION TIPO_INFRACCIONES "
    + "LEFT JOIN GPS_EVENTOS EVENTOS "
    +  "ON TIPO_INFRACCIONES.CD_TIPO_INFRACCION = SUBSTR(EVENTOS.EVENTO_INFRAC_NUM,1,2) " 
    +  "AND EVENTOS.EVENTO_TIPO_ID = 2 "
    +  "LEFT JOIN TMS003D_DISPOSITIVO_ZONA_VIAL ZONA_VIAL_DISP "
    +  "ON EVENTOS.EVENTO_DISPOSITIVO_ID = ZONA_VIAL_DISP.ID_DISPOSITIVO " 
    +  "AND ZONA_VIAL_DISP.ST_ACTIVO = 1 "
    +  "LEFT JOIN TMS002C_ZONA_VIAL ZONAV "
    +  "ON ZONAV.ID_ZONA_VIAL = ZONA_VIAL_DISP.ID_ZONA_VIAL "
    +  "WHERE  TIPO_INFRACCIONES.CD_TIPO_INFRACCION IN ('01', '04', '05', '06') "
    +  "AND ZONAV.ID_ZONA_VIAL = #{zonaVialId}" 
    +  "GROUP BY TIPO_INFRACCIONES.NB_TIPO_INFRACCION, ZONAV.NB_ZONA_VIAL, TIPO_INFRACCIONES.CD_TIPO_INFRACCION";
	
	String GET_INFRACCIONES_DIA_POR_ZONA_VIAL =
		"SELECT ZONAV.NB_ZONA_VIAL AS ZONAVIAL, " +
		"TIPO_INFRACCIONES.NB_TIPO_INFRACCION AS TIPOINFRACCION, TIPO_INFRACCIONES.CD_TIPO_INFRACCION AS CODIGOINFRACCION, " +
		"COUNT(EVENTOS.EVENTO_INFRAC_NUM) AS TOTALINFRACCIONES " +
		"FROM TSAI001C_TIPO_INFRACCION TIPO_INFRACCIONES " +
		"LEFT JOIN GPS_EVENTOS EVENTOS " +
		"ON TIPO_INFRACCIONES.CD_TIPO_INFRACCION = SUBSTR(EVENTOS.EVENTO_INFRAC_NUM,1,2) " +
		"AND EVENTOS.EVENTO_TIPO_ID = 2 " +
		"LEFT JOIN TMS003D_DISPOSITIVO_ZONA_VIAL ZONA_VIAL_DISP " +
		"ON EVENTOS.EVENTO_DISPOSITIVO_ID = ZONA_VIAL_DISP.ID_DISPOSITIVO " +
		"AND ZONA_VIAL_DISP.ST_ACTIVO = 1 " +
		"LEFT JOIN TMS002C_ZONA_VIAL ZONAV " +
		"ON ZONAV.ID_ZONA_VIAL = ZONA_VIAL_DISP.ID_ZONA_VIAL " +
		"WHERE  TIPO_INFRACCIONES.CD_TIPO_INFRACCION IN ('01', '04', '05', '06') " +
		"AND ZONAV.ID_ZONA_VIAL = #{zonaVialId} " +
		"AND  TRUNC(EVENTOS.EVENTO_FECHA_HORA,'DDD') = TO_DATE(#{dia}, 'DD-MM-YYYY hh:mi:ss') " +
		"GROUP BY TIPO_INFRACCIONES.NB_TIPO_INFRACCION, ZONAV.NB_ZONA_VIAL, TIPO_INFRACCIONES.CD_TIPO_INFRACCION " +
		"ORDER BY TIPO_INFRACCIONES.NB_TIPO_INFRACCION ASC " ;
	
	String GET_INFRACCIONES_MENSUAL_POR_ZONA_VIAL =
		"SELECT EXTRACT(YEAR FROM EVENTOS.EVENTO_FECHA_HORA) as yr, EXTRACT(MONTH FROM EVENTOS.EVENTO_FECHA_HORA) as MES, ZONAV.NB_ZONA_VIAL AS ZONAVIAL, " +
		"TIPO_INFRACCIONES.NB_TIPO_INFRACCION AS TIPOINFRACCION, TIPO_INFRACCIONES.CD_TIPO_INFRACCION AS CODIGOINFRACCION, " +
		"COUNT(EVENTOS.EVENTO_INFRAC_NUM) AS TOTALINFRACCIONES " +
		"FROM TSAI001C_TIPO_INFRACCION TIPO_INFRACCIONES " +
		"LEFT JOIN GPS_EVENTOS EVENTOS " +
		"ON TIPO_INFRACCIONES.CD_TIPO_INFRACCION = SUBSTR(EVENTOS.EVENTO_INFRAC_NUM,1,2) " +
		"AND EVENTOS.EVENTO_TIPO_ID = 2 " +
		"LEFT JOIN TMS003D_DISPOSITIVO_ZONA_VIAL ZONA_VIAL_DISP " +
		"ON EVENTOS.EVENTO_DISPOSITIVO_ID = ZONA_VIAL_DISP.ID_DISPOSITIVO " +
		"AND ZONA_VIAL_DISP.ST_ACTIVO = 1 " +
		"LEFT JOIN TMS002C_ZONA_VIAL ZONAV " +
		"ON ZONAV.ID_ZONA_VIAL = ZONA_VIAL_DISP.ID_ZONA_VIAL " +
		"WHERE  TIPO_INFRACCIONES.CD_TIPO_INFRACCION IN ('01', '04', '05', '06') " +
		"AND ZONAV.ID_ZONA_VIAL = #{zonaVialId} " +
		"AND EXTRACT(YEAR FROM EVENTOS.EVENTO_FECHA_HORA) = #{anio} " +
		"GROUP BY EXTRACT(YEAR FROM EVENTOS.EVENTO_FECHA_HORA), EXTRACT(MONTH FROM EVENTOS.EVENTO_FECHA_HORA), TIPO_INFRACCIONES.NB_TIPO_INFRACCION, ZONAV.NB_ZONA_VIAL, TIPO_INFRACCIONES.CD_TIPO_INFRACCION " +
		"ORDER BY YR DESC, MES ASC, TIPO_INFRACCIONES.NB_TIPO_INFRACCION ASC";
	
	String GET_INFRACCIONES_ANUAL_POR_ZONA_VIAL =
		"<script>SELECT EXTRACT(YEAR FROM EVENTOS.EVENTO_FECHA_HORA) as yr, ZONAV.NB_ZONA_VIAL AS ZONAVIAL, " +
		"TIPO_INFRACCIONES.NB_TIPO_INFRACCION AS TIPOINFRACCION, TIPO_INFRACCIONES.CD_TIPO_INFRACCION AS CODIGOINFRACCION, " +
		"COUNT(EVENTOS.EVENTO_INFRAC_NUM) AS TOTALINFRACCIONES " +
		"FROM TSAI001C_TIPO_INFRACCION TIPO_INFRACCIONES " +
		"LEFT JOIN GPS_EVENTOS EVENTOS " +
		"ON TIPO_INFRACCIONES.CD_TIPO_INFRACCION = SUBSTR(EVENTOS.EVENTO_INFRAC_NUM,1,2) " +
		"AND EVENTOS.EVENTO_TIPO_ID = 2 " +
		"LEFT JOIN TMS003D_DISPOSITIVO_ZONA_VIAL ZONA_VIAL_DISP " +
		"ON EVENTOS.EVENTO_DISPOSITIVO_ID = ZONA_VIAL_DISP.ID_DISPOSITIVO " +
		"AND ZONA_VIAL_DISP.ST_ACTIVO = 1 " +
		"LEFT JOIN TMS002C_ZONA_VIAL ZONAV " +
		"ON ZONAV.ID_ZONA_VIAL = ZONA_VIAL_DISP.ID_ZONA_VIAL " +
		"WHERE  TIPO_INFRACCIONES.CD_TIPO_INFRACCION IN ('01', '04', '05', '06') " +
		"AND ZONAV.ID_ZONA_VIAL = #{zonaVialId} " +
		"AND EXTRACT(YEAR FROM EVENTOS.EVENTO_FECHA_HORA) IN "
		+ "<foreach item='item' index='index' collection='anios' open='(' separator=',' close=')'>" +
		" #{item} " +
		" </foreach> " + 
		"GROUP BY EXTRACT(YEAR FROM EVENTOS.EVENTO_FECHA_HORA), TIPO_INFRACCIONES.NB_TIPO_INFRACCION, ZONAV.NB_ZONA_VIAL, TIPO_INFRACCIONES.CD_TIPO_INFRACCION " +
		"ORDER BY YR DESC, TIPO_INFRACCIONES.NB_TIPO_INFRACCION ASC</script>";
	
	@Select(GET_INFRACCIONES_POR_ZONA_VIAL)
    List<InfraccionesPorZonaVialVO> busquedaInfraccionesPorZonaVial(@Param("zonaVialId")Long perfilId);
	
	@Select(GET_INFRACCIONES_DIA_POR_ZONA_VIAL)
    List<InfraccionesPorZonaVialVO> busquedaInfraccionesDiaPorZonaVial(@Param("zonaVialId")Long perfilId, @Param("dia")String dia);
	
	@Select(GET_INFRACCIONES_MENSUAL_POR_ZONA_VIAL)
    List<InfraccionesPorZonaVialVO> busquedaInfraccionesMensualPorZonaVial(@Param("zonaVialId")Long perfilId, @Param("anio")Integer anio);
	
	@Select(GET_INFRACCIONES_ANUAL_POR_ZONA_VIAL)
    List<InfraccionesPorZonaVialVO> busquedaInfraccionesAnualPorZonaVial(@Param("zonaVialId")Long perfilId, @Param("anios")List<Integer> anios);
}